ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/cci
obj-$(CONFIG_LENOVO_EEPROM) += msm_eeprom.o
