ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/cci
obj-$(CONFIG_LENOVOB_CAMERA) += msm_actuator.o
obj-$(CONFIG_LENOVO_AF_LASER) += stmvl6180.o
obj-$(CONFIG_LENOVO_EEPROM_ONSEMI) += onsemi_cmd.o
obj-$(CONFIG_LENOVO_EEPROM_ONSEMI_OIS) += onsemi_ois_init.o
