ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera-lenovo/camera-driver/sensor/cci
obj-$(CONFIG_LENOVO_AF_LASER) += vl6180x_api.o vl6180x_i2c.o
